const { google } = require('googleapis');

const SPREADSHEET_ID = process.env.GOOGLE_SHEETS_SPREADSHEET_ID;

const isConfigured = () =>
  Boolean(SPREADSHEET_ID && process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL && process.env.GOOGLE_PRIVATE_KEY);

const getSheetsClient = () => {
  const auth = new google.auth.GoogleAuth({
    credentials: {
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
    },
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  return google.sheets({
    version: 'v4',
    auth,
  });
};

const HEADER_ROW = [
  'Candidate Name',
  'Email',
  'Designation',
  'Department',
  'Employment Type',
  'Duration (months)',
  'Date of Joining',
  'End Date',
  'Stipend / CTC',
  'Reporting Manager',
  'Email Status',
  'Generated By',
  'Offer ID',
  'Last Updated',
];

const formatDate = (d) => (d ? new Date(d).toISOString().split('T')[0] : '');

const offerToRow = (offer, generatedByName) => [
  offer.candidateName,
  offer.candidateEmail,
  offer.designation,
  offer.department,
  offer.employmentType,
  offer.internshipDurationMonths || '',
  formatDate(offer.dateOfJoining),
  formatDate(offer.endDate),
  offer.stipendOrCTC,
  offer.reportingManager || '',
  offer.emailStatus,
  generatedByName || '',
  offer._id.toString(),
  new Date().toISOString(),
];

// Creates a tab named after the department if it doesn't exist yet,
// with the header row already in place.
const ensureDepartmentSheet = async (sheets, department) => {
  const meta = await sheets.spreadsheets.get({ spreadsheetId: SPREADSHEET_ID });
  const exists = meta.data.sheets.some((s) => s.properties.title === department);
  if (exists) return;

  await sheets.spreadsheets.batchUpdate({
    spreadsheetId: SPREADSHEET_ID,
    requestBody: { requests: [{ addSheet: { properties: { title: department } } }] },
  });
  await sheets.spreadsheets.values.update({
    spreadsheetId: SPREADSHEET_ID,
    range: `${department}!A1`,
    valueInputOption: 'RAW',
    requestBody: { values: [HEADER_ROW] },
  });
};

// Looks for a row already tagged with this offer's ID (column M) so
// resend/edit updates the existing row instead of creating a duplicate.
const findExistingRowNumber = async (sheets, department, offerId) => {
  const range = `${department}!A2:N`;
  const res = await sheets.spreadsheets.values.get({ spreadsheetId: SPREADSHEET_ID, range });
  const rows = res.data.values || [];
  const idx = rows.findIndex((row) => row[12] === offerId.toString());
  return idx === -1 ? null : idx + 2; // +2: sheet rows are 1-indexed, offset past the header
};

// Best-effort sync - never throws. Returns { success, error? } so the
// caller can record sheetSyncStatus without the offer flow ever failing
// because of a spreadsheet problem.
const upsertOfferRow = async (offer, generatedByName) => {
  if (!isConfigured()) {
    return { success: false, error: 'Google Sheets is not configured (missing env vars)' };
  }

  try {
    const sheets = getSheetsClient();
    await ensureDepartmentSheet(sheets, offer.department);

    const row = offerToRow(offer, generatedByName);
    const existingRowNumber = await findExistingRowNumber(sheets, offer.department, offer._id);

    if (existingRowNumber) {
      await sheets.spreadsheets.values.update({
        spreadsheetId: SPREADSHEET_ID,
        range: `${offer.department}!A${existingRowNumber}:N${existingRowNumber}`,
        valueInputOption: 'RAW',
        requestBody: { values: [row] },
      });
    } else {
      await sheets.spreadsheets.values.append({
        spreadsheetId: SPREADSHEET_ID,
        range: `${offer.department}!A2`,
        valueInputOption: 'RAW',
        insertDataOption: 'INSERT_ROWS',
        requestBody: { values: [row] },
      });
    }

    return { success: true };
  } catch (err) {
    return { success: false, error: err.message };
  }
};

// Called once at server boot (see server.js). Just confirms the
// credentials actually authenticate and can read the spreadsheet -
// catches misconfiguration immediately instead of on the first offer.
const verifyGoogleSheetsConnection = async () => {
  if (!isConfigured()) {
    console.warn('Google Sheets sync is not configured (GOOGLE_* env vars missing) - skipping sync.');
    return;
  }
  try {
    const sheets = getSheetsClient();
    const meta = await sheets.spreadsheets.get({ spreadsheetId: SPREADSHEET_ID });
    console.log(`Google Sheets connected: "${meta.data.properties.title}"`);
  } catch (err) {
    console.warn('Google Sheets connection failed:', err.message);
    console.warn(
      'Check: (1) all 3 GOOGLE_* vars are set in .env, (2) GOOGLE_PRIVATE_KEY is wrapped in quotes with literal \\n sequences, (3) the spreadsheet is shared with the service account email as Editor, (4) the Sheets API is enabled on the project.'
    );
  }
};

module.exports = { upsertOfferRow, isConfigured, verifyGoogleSheetsConnection };
